name: CI-AzureKubeHelmRunner-v0.$(date:yy)$(DayOfYear)$(rev:.r)

trigger:
- master
- Issue*

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: VersionExtractor@5
  name: build
  displayName: 'Version extractor digit'
  inputs:
    stringToAnalyze: '$(Build.BuildNumber)'

- task: Docker@2
  displayName: 'Build hub.docker.com'
  inputs:
    containerRegistry: 'docker-lturmel'
    repository: 'lturmel/AzureKubeHelmRunner'
    command: 'build'
    Dockerfile: '**/Dockerfile'
    tags: |
      $(build.fullVersion)
      latest